name: vizinhanca_shop
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  carousel_slider: ^5.0.0
  firebase_core: ^3.12.1
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.14.3
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.4.5
  geocoding: ^3.0.0
  geolocator: ^13.0.2
  get_it: ^8.0.3
  google_fonts: ^6.2.1
  google_sign_in: ^6.2.2
  http: ^1.3.0
  image_picker: ^1.1.2
  intl: ^0.19.0
  mask_text_input_formatter: ^2.9.0
  shared_preferences: ^2.5.2
  smooth_page_indicator: ^1.2.1
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/logos/
